language: go
go: 1.14.x
services:
  - docker

before_script:
  - sudo curl -fsSL https://goss.rocks/install | sudo sh

script:
  - docker build --file Containerfile --tag aws-ec2-exporter:testing .
  - GOSS_FILES_PATH=test dgoss run aws-ec2-exporter:testing
